
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
array = [i for i in range (10)]
print(array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [2]:
import numpy as np 

array = np.array([i for i in range(9)])
matrix = np.reshape(array, (3,3))
print((matrix))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Access the element at the second row, second column.


In [3]:
import numpy as np 

array = np.array([i for i in range(9)])
matrix = np.reshape(array, (3, 3))

element = matrix[1, 1]
print(element)


4


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [4]:
import numpy as np
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

#add
add_result = array1 + array2
print("Addition:", add_result)

#sub
sub_result = array1 - array2
print("subsctration:", sub_result)

#mult
mult_result = array1 * array2
print("multiplication:",mult_result)

#Division
division_result = array1 / array2
print("division:", division_result)

Addition: [5 7 9]
subsctration: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [5]:
import numpy as np 

array = np.array([1,2,3,4,5])

#sum
array_sum = np.sum(array)
print("sum:", array_sum)

#mean
array_mean = np.mean(array)
print("mean:", array_mean)

# standard deviation 
array_std_dev = np.std(array)
print("standard deviation:", array_std_dev)

sum: 15
mean: 3.0
standard deviation: 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [6]:
import numpy as np 

array = np.array([1,2,3,4,5,6])

# reshape into a 2x3 array
reshaped_array = np.reshape(array,(2,3))

print(reshaped_array)






[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [7]:
import numpy as np

# Create a 5x5 array with random integers between 0 and 9
array = np.random.randint(0, 10, size=(5, 5))

print("Original Array:")
print(array)

# Define the specific value
specific_value = -1

# Define the indices of the sub-array
row_start, row_end = 2, 4  # Rows 2 to 3
col_start, col_end = 2, 4  # Columns 2 to 3

# Replace the values in the sub-array with the specific value
array[row_start:row_end, col_start:col_end] = specific_value

print("\nArray after replacement:")
print(array)


Original Array:
[[3 5 4 8 9]
 [2 2 0 1 1]
 [0 3 0 3 3]
 [5 9 5 1 0]
 [1 6 4 8 6]]

Array after replacement:
[[ 3  5  4  8  9]
 [ 2  2  0  1  1]
 [ 0  3 -1 -1  3]
 [ 5  9 -1 -1  0]
 [ 1  6  4  8  6]]


Replace all values in the sub-array with a specific value.


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [8]:
import numpy as np

array = np.array([[1,2],[3,4],[5,6],[7,8]])

subarray = array[1:3, :]
print(subarray)

[[3 4]
 [5 6]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [14]:
import numpy as np 

array = np.array(3).reshape(3,1) + np.array(3)

print(array)

ValueError: cannot reshape array of size 1 into shape (3,1)

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [15]:
import numpy as np

# Create the 2D array
array_2d = np.arange(3).reshape(3, 1) + np.arange(3)

# Create the 1D array
array_1d = np.array([1, 2, 3])

# Add the 1D array to each row of the 2D array using broadcasting
result = array_2d + array_1d

print(result)


[[1 3 5]
 [2 4 6]
 [3 5 7]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [16]:
import numpy as np

# Create the first 2D array with random integers
array1 = np.random.randint(0, 10, size=(3, 3))

# Create the second 2D array with random integers
array2 = np.random.randint(0, 10, size=(3, 3))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

Array 1:
[[8 3 7]
 [9 6 9]
 [1 1 3]]

Array 2:
[[3 3 3]
 [9 3 8]
 [3 5 9]]


In [17]:
import numpy as np

# Create the first 2D array with random integers
array1 = np.random.randint(0, 10, size=(3, 3))

# Create the second 2D array with random integers
array2 = np.random.randint(0, 10, size=(3, 3))

# Concatenate them horizontally
horizontal_concatenated = np.concatenate((array1, array2), axis=1)

# Concatenate them vertically
vertical_concatenated = np.concatenate((array1, array2), axis=0)

print("Horizontally concatenated:")
print(horizontal_concatenated)

print("\nVertically concatenated:")
print(vertical_concatenated)


Horizontally concatenated:
[[7 7 6 0 2 8]
 [3 0 8 3 3 9]
 [7 4 9 2 2 1]]

Vertically concatenated:
[[7 7 6]
 [3 0 8]
 [7 4 9]
 [0 2 8]
 [3 3 9]
 [2 2 1]]


In [18]:
import numpy as np

# Create the first 2D array with random integers
array1 = np.random.randint(0, 10, size=(3, 3))

# Create the second 2D array with random integers
array2 = np.random.randint(0, 10, size=(3, 3))

# Concatenate them horizontally
horizontal_concatenated = np.concatenate((array1, array2), axis=1)

# Concatenate them vertically
vertical_concatenated = np.concatenate((array1, array2), axis=0)

# Split horizontally concatenated array back into original arrays
array1_split_h, array2_split_h = np.split(horizontal_concatenated, 2, axis=1)

# Split vertically concatenated array back into original arrays
array1_split_v, array2_split_v = np.split(vertical_concatenated, 2, axis=0)

print("Horizontally split:")
print("Array 1:")
print(array1_split_h)
print("\nArray 2:")
print(array2_split_h)

print("\nVertically split:")
print("Array 1:")
print(array1_split_v)
print("\nArray 2:")
print(array2_split_v)


Horizontally split:
Array 1:
[[6 6 8]
 [6 8 1]
 [5 8 3]]

Array 2:
[[4 3 2]
 [7 2 1]
 [0 5 5]]

Vertically split:
Array 1:
[[6 6 8]
 [6 8 1]
 [5 8 3]]

Array 2:
[[4 3 2]
 [7 2 1]
 [0 5 5]]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

